---
title: "Syllabus"
subtitle: "Automated Data Collection with R - Fall 2024 - University of Mannheim"
editor: 
  markdown: 
    wrap: 72
---

## **Course details**

|               |                                                                                              |
|--------------------------|----------------------------------------------|
| Seminar:      | Übung - Methoden der Vergleichenden Regierungslehre                                          |
| Time:         | Thursday, 13:45 – 15:15, September 05 to December 05                                         |
| Place:        | C -108 Methodenlabor - groß/ Telefonlabor (A 5, 6 Bauteil C)                                 |
| Language:     | English                                                                                      |
| Instructor:   | David Schweizer, M.A., david.schweizer\@uni-mannheim.de                                      |
| Office hours: | In-person (A 340) or via Zoom, Thursday 15:30 -- 16:30, please make an appointment by e-mail |

## **Course description**

**\
**Against the background of the ever-increasing availability of
(unstructured) online data, the goal of this course is to equip the
students with the necessary skills to collect large quantities of data
for their own research projects, to process the data, and to automate
this workflow in a reproducible way.

\
The course introduces students to automated data collection using a very
practical approach with the R programming language. The course consists
of three major modules. First, you will be guided into the programming
language learning the fundamentals of R and the data science workflow:
Import, tidy, transform, & visualize data. No prior experience with R is
necessary! Second, we will focus on the workflow for reproducible
research and how to communicate our results, also in an interactive way.
For example, this includes version control via Github. Third, we will
cover static and dynamic web scraping as well as APIS’s from a
conceptual perspective and use these tools to collect web data. Finally,
we will also learn how to automate this process.

The goal of this course is to equip you with the skills to:

-   collect your own data

-   tidy, transform & visualize the data

-   communicate your data interactively & (exploratory) results

-   collaborate with others along the workflow

Taking this course should not be an end in itself. The motivation for
this course is therefore twofold: First, these skills prepare you for
conducting empirical research (including term papers, BA or MA theses),
collaborating with other students / researchers, and communicating your
work. Second, mastering these skills also prepare you for a career
outside academia.

There are no prerequisites for this course, except the willingness to
familiarise yourself with the R programming language.

## **Course requirements**

### **Active participation and preparation:**

Active participation during our weekly sessions is important to get the
most out of this course. Engaging with the assigned readings is
essential for participation.

Use ILIAS to post any questions or discuss with your peers if you do not
understand concepts. I will also regularly check the ILIAS forum
("Discussion & Questions").

### **Short assignment during the semester (10% of your grade)**

There will be two short assignments during the semester. Here, you have
to demonstrate that you can apply the concepts/code presented during the
session on your own.

Deadlines:

-   Assignment 1: 19.09.2024 after the session -\> 04.10.2024 15:15
-   Assignment 2: 17.10.2024 after the session -\> 31.10.2024 15:15

### **Group data project (90% of your grade: 15% presentation of proposal):**

***In a nutshell: Ask a question you’re curious about, collect
(webscrape) relevant data and visualize them with regard to your
question.***

Instead of a term paper, you will work on a data project. Again, in this
final assignment, you need to demonstrate you understanding of the
concepts/code covered during the semester. The goal is that you build
your own data set using web scraping methods and present this data set.
Hence, the data project includes the following steps:

-   Collect own data using web scraping methods

-   Tidy and transform the data

-   Possibly enrich the data set with other data (sets)

-   Visualize your data

-   Present your data set using an interactive web application or an
    (interactive Quarto document)

-   Describe: How could you or other researchers make use of this data
    for empirical research - What might be possible research questions?

**Group work** (2 or 3 students). In case of group work, each student
will receive the same grade.

#### **Timeline & Submission**

-   Form groups until 10.10.2024: 2 or 3 students

-   Data project proposals until 07.11.2024: Come up with at least two
    project proposals and discuss them during office hours. Outline your
    motivation, a possible research questions, and identify data sources
    (for webscraping).

-   Data project proposal presentations at 05.12.2024: Presentation
    should last no longer than ten minutes. Introduce the topic, your
    motivation, and the data source. Outline how you scrape the data.
    Include a first glimpse at the data.

-   Deadline for the data project**:** December 26, 2024, 23:59.

    -   Submission via ILIAS (zip folder: This should include your code
        for the Shiny dashboard, R.data files, any R scripts for
        pre-processing, as well as raw data).

-   **In case of any questions or problems, please get in touch with me
    as early as possible.** Late submission will result in grade
    deductions.

#### **Grading of the project will take into account the following:**

-   Data collection: Correct? "Polite"? Documentation?

-   Data transformation: Correct? Documentation/Annotation?

-   Communication (Visualization(s) via dashboard): Correct? Style?
    Effort?

-   Collaboration: Working together via Github

-   Reproducibility: Can the dashboard and all pre-processing steps
    executed on another device without error? (You need to hand in the
    code for the shiny dashboard, R.data files, any R scripts for
    pre-processing, and the raw data.)

-   *BONUS: Creativity and Critical Thought - Is the project carefully
    thought out? How well is the project documented? Does it appear that
    time and effort went into the planning and implementation of the
    project?*

**A general breakdown of scoring is as follows:**

-   *1,0: Outstanding effort.* Student understands how to apply all
    concepts o the seminar, can collect data via webscraping "politely",
    transform and visualize the data coherently and convincingly, and do
    so in a reproducible way.

-   *1,3 - 2,0: Good effort.* Student seems to understand most of the
    concepts and there are only minor mistakes regarding data collection
    and transformation. Communication could be clearer and/or the
    project is not fully reproducible.

-   *2,3 - 3,0: Good/Passing effort.* Student has misunderstanding of
    concepts in several areas, has some trouble with data collection and
    transformation, and the communication of results is sometimes
    unclear. Further, the project is not fully reproducible and it is
    visible that little effort went into the project.

-   *3,3 - 4,0: Struggling effort.* Student is making some effort, but
    has misunderstanding of many concepts and is unable to put together
    the workflow of the data project. Communication is unclear, the
    project is not reproducible.

-   *Fail*: Student is not making a sufficient effort.

## **Organization & Learning Resources**

**Course website and ILIAS:**

The plan is to use primarily the course website and ILIAS for providing
the structure of the seminar, materials, and communication,
respectively. You will also receive mails via ILIAS regarding
announcements etc. Make sure to regularly check your university e-mail
address.

If you have contacted me with a question and you did not hear back after
2 days (except over the weekend), please just send me your question
again!

**Office hours:**

-   In-person (A 340) or via Zoom, Thursday 15:30 -- 16:30, please make
    an appointment by e-mail.

-   If you have a specific question or problem (e.g., installing a
    specific package, finding a data source, etc.), please let me know
    before coming to the office hours. This way , I can also prepare for
    it and thereby making our meeting more productive and constructive.

**Illness (& Covid)**

-   If you feel ill or have symptoms, please be considerate of your
    fellow students and yourself(!). Just let me know by e-mail.

**Students with disabilities or chronic illnesses:**

-   Please contact me or the Office of Student Affairs if you need
    special assistance due to disabilities or chronic illnesses. And
    please do this early in the semester so that we can make the
    appropriate arrangements.

**If you need any support:**

Of course, you can always talk directly to me if you feel comfortable
with the question. It is important to note that the [University's
Equality and Diversity
Office](https://www.uni-mannheim.de/gleichstellung/beratung/) supports
and advises you in cases of discrimination or sexual harassment. The
responsible contact person in such a case is Dipl.-Psych. Ute Pfründer.
She is trained to deal with such incidents and will keep everything
strictly confidential. No action will be taken without your express
consent. Further counseling services offered by the university can be
found via this
[link](https://www.uni-mannheim.de/studium/beratung-und-service/beratungswegweiser/).

**Readings**

The primary readings for this seminar are chapters from the following
books:

-   Healy, Kieran. *Data visualization: a practical introduction*.
    Princeton University Press, 2018. *Free access via Katalog Primo and
    free online: https://socviz.co/*

-   Wilke, Claus E. *Fundamentals of Data Visualization*. O'Reilly
    Media, 2018. *Free access via Katalog Primo and free online:
    https://clauswilke.com/dataviz/*

-   Wickham, H., Çetinkaya-Rundel, M., & Grolemund, G. (2023). *R for
    data science. 2ed*". O'Reilly Media, Inc. *Free online:*
    <https://r4ds.hadley.nz/>

You will receive the reading materials for the next session always after
our weekly sessions.

## **Course Schedule**

The schedule is preliminary. Structure and/or content might change
during the semester. You will find the readings, materials, and slides
for each week on the course website (see *Schedule, slides &
materials*).

**Intro**

Week 01 - 05.09.2024 - Intro Session

**Block I: Import, Tidy, & Transform Data**

Week 02 - 12.09.2024 - Intro to R

Week 03 - 19.09.2024 - Tidyverse I: Import, tidy, and transform

Week 04 - 26.09.2024 - No Session

Week 05 - 03.10.2024 - No Session, Public Holiday

Week 06 - 10.10.2024 - Tidyverse II: Import, tidy, and transform

**Block II: Visualize, Communicate & Collaborate**

Week 07 - 17.10.2024 - ggplot: Visualize

Week 08 - 24.10.2024 - Quarto & Version control (Github)

**Block III: Web scraping**

Week 09 - 31.10.2024 - Web scraping basics

Week 10 - 07.11.2024 - Web scraping static

Week 11 - 14.11.2024 - Web scraping dynamic

**Block II: Communicate Interactively**

Week 12 - 21.11.2024 - Interactive I: Create your first Shiny app

Week 13 - 28.11.2024 - Interactive II: Making pretty Shiny apps app

**Closing**

Week 14 - 05.12.2024 - Closing Session: Presentations
